### ISSUE TITLE
List of tools that would have to be updated after source map spec changes

### ISSUE THREAD

**Issue by jkrems** [tc39/source-map#13]
1. DevTools (e.g. Chrome/Firefox)
2. Minimizer (e.g. terser/SWC/esbuild/closure-compiler)
3. Bundler (e.g. parcel/webpack/rollup/esbuild/closure-compiler)
4. Transpilers (e.g. TS/babel/SWC/CoffeeScript/closure-compiler)
5. Telemetry (e.g. Sentry.io)

**Comment by rbuckton** [comment]
- Source map visualizers
- Host engines that support source maps for stack traces (outside of devtools)
- Maybe devtools related, but tools like https://github.com/rbuckton/deoptexplorer-vscode uses source maps to walk back to source when analyzing IC events in v8 logs.

Other dev tools of note: VS Code (i.e., https://github.com/microsoft/vscode-js-debug)

**Comment by jkup** [comment]
Added https://github.com/jkup/source-map-users to CONTRIBUTING.md
