### ISSUE TITLE
Future of X- Prefixes

### ISSUE THREAD

**Issue by mitsuhiko** [tc39/source-map#25]
I have no strong opinions here but I came across this again. HTTP no longer recommends `x-` prefixes, the future of `x_` prefixes in this specification should maybe be reconsidered.

At least I would argue that we should not recommend vendor prefixes. If we think for instance that `ignoreList` is a useful thing, it's odd that all tools are supposed to refer to this as `x_google_ignoreList`.

**Comment by littledan** [comment]
We use some vendor prefixes at Bloomberg. I'm not really sure if vendor prefixes are a bad thing here.

**Comment by bmeurer** [comment]
My 2 cents here is that vendor prefixes are a quite useful way to experiment with new ideas. Let's take the case of `x_google_ignoreList`: The vendor prefix allowed us to experiment with this and get this in front of real users to understand whether we are really solving the right problem here, and we can now bring that understanding to the standards body to agree on how to properly standardize it (which could be as simple as removing the `x_google_` from the beginning and having tools support both `x_google_ignoreList` and `ignoreList` for a few releases).

**Comment by jkup** [comment]
Since Google and Mozilla seem happy with this, can we add an official `ignoreList` to the spec? @mitsuhiko brought up a good point about what to do if both show up. Let's talk about this further.

For x-prefixes in general, this seems like it merits more discussion.

**Comment by EricSL** [comment]
For the x_google_ignoreList change, I made a pull request: https://github.com/tc39/source-map-spec/pull/19

**Comment by littledan** [comment]
Will be fixed by https://github.com/tc39/source-map-spec/pull/24
