### ISSUE TITLE
WebAssembly source-map integration

### ISSUE THREAD

**Issue by littledan** [tc39/source-map#8]
@dschuff [has proposed](https://github.com/WebAssembly/design/pull/1051) source-map support for WebAssembly. Should we upstream the definitions here into the source-maps specification, or should it be defined in the WebAssembly specification?

**Comment by jkup** [comment]
@JSMonk, @jaro-sevcik and @bomsy is this closeable? We updated the spec to have column information for WASM. Is there more work we need to do here?

**Comment by JSMonk** [comment]
I don't think so. @bashor do you have any ideas?

**Comment by bashor** [comment]
It would be nice to add information about how wasm binary references (is linked) with map file [here](https://tc39.es/source-map-spec/#linking-generated-code)

**Comment by bashor** [comment]
It's described here — https://github.com/WebAssembly/tool-conventions/blob/main/Debugging.md#source-maps

**Comment by bashor** [comment]
One thing that is omitted there is that the string is encoded in `UTF8`.

**Comment by jkup** [comment]
I think @JSMonk merged all these in!
